sonar.projectKey=nextjs-app
sonar.projectName=NextJS App
sonar.projectVersion=1.0

sonar.sources=.

sonar.language=js

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.exclusions=node_modules/**,.next/**,coverage/**
sonar.token=squ_3ddce97f94f620d5507e90799f52b856b84f8f48
sonar.javascript.lcov.reportPaths=coverage/lcov.info